<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR', WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . "product-variations-swatches-for-woocommerce" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . "includes" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_ADMIN', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "admin" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_FRONTEND', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "frontend" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_LANGUAGES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . "languages" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_TEMPLATES', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "templates" . DIRECTORY_SEPARATOR );
$plugin_url = plugins_url( '',__FILE__ );
$plugin_url = str_replace( '/includes', '', $plugin_url );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_CSS', $plugin_url . "/assets/css/" );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_CSS_DIR', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . "assets/css" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_JS', $plugin_url . "/assets/js/" );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_JS_DIR', VI_WOO_PRODUCT_VARIATIONS_SWATCHES_DIR . "assets/js" . DIRECTORY_SEPARATOR );
define( 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_IMAGES', $plugin_url . "/assets/images/" );

/*Include functions file*/
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "functions.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "functions.php";
}
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "support.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "support.php";
}
if ( is_file( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "data.php" ) ) {
	require_once VI_WOO_PRODUCT_VARIATIONS_SWATCHES_INCLUDES . "data.php";
}
vi_include_folder( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_ADMIN, 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_Admin_' );
vi_include_folder( VI_WOO_PRODUCT_VARIATIONS_SWATCHES_FRONTEND, 'VI_WOO_PRODUCT_VARIATIONS_SWATCHES_Frontend_' );
